### ISSUE TITLE
Chat spammed with expired notifications when not relevant

### ISSUE THREAD

**Issue by Qenthel94** [shemetz/pf2e-extempore-effects#34]
Previously there was an option to only have secret effects post a notification in chat, which was great as they were the most relevant ones to get a reminder now. Now there is just "all effect" or "no effects" option and it causes some issues with player effects. With stuff like 8 hour long buffs, treat wounds/battle medicine immunity etc every time a longer amount of time passes the chat gets flooded with like 20 messages with maybe 2 being relevant for the effect to be re-applied. ;/
Is there a way to go back to the having a notification only for secret effects?

**Comment by shemetz** [comment]
Dang, when I removed it I thought there was no legitimate use case, but you're proving me wrong.

I think limiting it only to secret effects is bad though, because many people play with non-secret afflictions and want the reminders for them.

Perhaps I should add a list of "don't remind me when these expire" effects, which is hardcoded to include the treat wounds immunity effect and anything else suggested here?

**Comment by shemetz** [comment]
Okay, I re-added this setting in the new v1.8.4 (no idea what took me so long...), the default is just to remind on all effects rather than only secret ones.
